import { ISignInTemplateProps } from "../../../../interfaces/template/SignInTemplate";

const specializationOptions = [
    "Direito Civil",
    "Direito Penal",
    "Direito Trabalhista",
    "Direito Tributário",
    "Direito Previdenciário",
    "Direito Empresarial",
];

export const getInitialLawyerData = (
    name: string,
    onNameChange: (text: string) => void,
    cpf: string,
    onCpfChange: (text: string) => void,
    oabNumber: string,
    onOabNumberChange: (text: string) => void,
    email: string,
    onEmailChange: (text: string) => void,
    uf: string,
    onUfChange: (value: string) => void,
    specializations: string[],
    onSpecializationsChange: (values: string[]) => void,
    password: string,
    onPasswordChange: (text: string) => void,
    showPassword: boolean,
    onToggleShowPassword: () => void
): ISignInTemplateProps => ({
    title: "Cadastro de Advogado",
    description:
        "Solicite seu acesso profissional para começar a atender cidadãos na plataforma.",
    fields: [
        {
            label: "Nome completo",
            placeholder: "Nome completo conforme OAB",
            keyboardType: "default",
            leftIcon: true,
            rightIcon: false,
            iconSize: 24,
            iconNameProps: "person",
            type: "name",
            value: name,
            onChangeText: onNameChange,
        },
        {
            label: "CPF",
            placeholder: "000.000.000-00",
            keyboardType: "numeric",
            leftIcon: true,
            rightIcon: false,
            iconSize: 24,
            iconNameProps: "badge",
            type: "cpf",
            value: cpf,
            onChangeText: onCpfChange,
        },
        {
            label: "Número OAB",
            placeholder: "000.000",
            keyboardType: "numeric",
            leftIcon: true,
            rightIcon: false,
            iconSize: 24,
            iconNameProps: "badge",
            type: "text",
            value: oabNumber,
            onChangeText: onOabNumberChange,
        },
        {
            label: "UF da OAB",
            value: uf[0],
            onValueChange: onUfChange,
        },
        {
            label: "Especialização Principal",
            values: specializations,
            options: specializationOptions,
            onValuesChange: onSpecializationsChange,
        },
        {
            label: "E-mail profissional",
            placeholder: "email@exemplo.com.br",
            keyboardType: "email-address",
            leftIcon: true,
            rightIcon: false,
            iconSize: 24,
            iconNameProps: "email",
            type: "email",
            value: email,
            onChangeText: onEmailChange,
        },
        {
            label: "Senha",
            placeholder: "••••••••",
            secureTextEntry: !showPassword,
            leftIcon: true,
            rightIcon: true,
            rightIconName: showPassword ? "visibility-off" : "visibility",
            iconSize: 24,
            iconNameProps: "lock-outline",
            type: "password",
            value: password,
            onChangeText: onPasswordChange,
            onRightIconPress: onToggleShowPassword,
        },
    ],
});

