import { ISignInTemplateProps } from "../../../../../@/src/interfaces/template/SignInTemplate";

export const getInitialCitizenData = (
  name: string,
  onNameChange: (text: string) => void,
  cpf: string,
  onCpfChange: (text: string) => void,
  phone: string,
  onPhoneChange: (text: string) => void,
  email: string,
  onEmailChange: (text: string) => void,
  password: string,
  onPasswordChange: (text: string) => void,
  showPassword: boolean,
  onToggleShowPassword: () => void,
): ISignInTemplateProps => ({
  title: "Cadastro de Cidadão",
  description: "Faça seu cadastro para transformar sua indignação em mudança",
  fields: [
    {
      label: "Nome completo",
      placeholder: "Digite seu nome completo",
      keyboardType: "default",
      leftIcon: true,
      rightIcon: false,
      iconSize: 24,
      iconNameProps: "person",
      type: "name",
      value: name,
      onChangeText: onNameChange,
    },
    {
      label: "CPF",
      placeholder: "000.000.000-00",
      keyboardType: "numeric",
      leftIcon: true,
      rightIcon: false,
      iconSize: 24,
      iconNameProps: "badge",
      type: "cpf",
      value: cpf,
      onChangeText: onCpfChange,
    },
    {
      label: "Telefone",
      placeholder: "(00) 00000-0000",
      keyboardType: "phone-pad",
      leftIcon: true,
      rightIcon: false,
      iconSize: 24,
      iconNameProps: "phone",
      type: "phone",
      value: phone,
      onChangeText: onPhoneChange,
    },
    {
      label: "E-mail",
      placeholder: "email@exemplo.com",
      keyboardType: "email-address",
      leftIcon: true,
      rightIcon: false,
      iconSize: 24,
      iconNameProps: "email",
      type: "email",
      value: email,
      onChangeText: onEmailChange,
    },
    {
      label: "Senha de acesso",
      placeholder: "••••••••",
      secureTextEntry: !showPassword,
      leftIcon: true,
      rightIcon: true,
      rightIconName: showPassword ? "visibility-off" : "visibility",
      iconSize: 24,
      iconNameProps: "lock-outline",
      type: "password",
      value: password,
      onChangeText: onPasswordChange,
      onRightIconPress: onToggleShowPassword,
    },
  ],
});
