import { ISignInTemplateProps } from "../../../../interfaces/template/SignInTemplate";

export const getInitialSignInData = (
  email: string,
  onEmailChange: (text: string) => void,
  password: string,
  onPasswordChange: (text: string) => void,
  showPassword: boolean,
  onToggleShowPassword: () => void
): ISignInTemplateProps => ({
  layout: "login",
  showHeader: false,
  title: "Entrar no VozJusta",
  description: "Acesse sua conta para continuar",
  descriptionToFieldsSpacing: 32,
  submitLabel: "Entrar",
  showTerms: false,
  showForgotPassword: true,
  forgotPasswordRoute: "/screens/auth/ForgotPassword/Email",
  showSocialGoogle: true,
  footerPrefixText: "Ainda não tem conta?",
  footerActionText: "Cadastre-se",
  footerActionRoute: "/screens/Onboarding/roles",
  footerActionTextClassName: "text-[#fff]/80 underline font-semibold",
  fields: [
    {
      label: "E-mail",
      placeholder: "seu@email.com",
      keyboardType: "email-address",
      leftIcon: true,
      rightIcon: false,
      iconSize: 24,
      iconNameProps: "email",
      type: "email",
      value: email,
      onChangeText: onEmailChange,
    },
    {
      label: "Senha",
      placeholder: "••••••••",
      secureTextEntry: !showPassword,
      leftIcon: true,
      rightIcon: true,
      rightIconName: showPassword ? "visibility-off" : "visibility",
      iconSize: 24,
      iconNameProps: "lock-outline",
      type: "password",
      value: password,
      onChangeText: onPasswordChange,
      onRightIconPress: onToggleShowPassword,
    },
  ],
});
