import { ISignInTemplateProps } from "../../../../../../src/interfaces/template/SignInTemplate";

const specializationOptions = [
  "Administrativo", "Aduaneiro", "Assessoria Jurídica",
  "Aeronáutico","Agrário", "Ambiental", "Arbitragem",
  "Direitos Autorais", "Bancário e Financeiro", "Biotecnologia",
  "Civil", "Comercial", "Comércio Internacional", "Concorrencial",
  "Constitucional", "Consumidor", "Contratos Comerciais", "Desportivo",
  "Direito das Águas", "Terceiro Setor", "Econômico", "Eleitoral",
  "Penal Empresarial", "Energia", "Falimentar", "Família", "Fusões e Aquisições",
  "Imobiliário", "Importação e Exportação", "Infraestrutura", "Internacional",
  "Internet e Comércio Eletrônico", "Marítimo", "Mercado de Capitais",
  "Minerário", "Operações Financeiras", "Penal",
  "Óleo e Gás","Previdenciário", "Financiamento de Projetos",
  "Propriedade Intelectual", "Reestruturação Empresarial", "Regulatório",
  "Saúde e Sanitário", "Seguros", "Sindical",
  "Societário", "Telecomunicações", "Trabalhista", "Tributário",
];

export const getInitialLawyerData = (
  name: string,
  onNameChange: (text: string) => void,
  cpf: string,
  onCpfChange: (text: string) => void,
  oabNumber: string,
  onOabNumberChange: (text: string) => void,
  email: string,
  onEmailChange: (text: string) => void,
  uf: string,
  onUfChange: (value: string) => void,
  specialization: string,
  onSpecializationChange: (value: string) => void,
  password: string,
  onPasswordChange: (text: string) => void,
  showPassword: boolean,
  onToggleShowPassword: () => void,
): ISignInTemplateProps => ({
  title: "Cadastro de Advogado",
  description:
    "Solicite seu acesso profissional para começar a atender cidadãos na plataforma.",
  fields: [
    {
      label: "Nome completo",
      placeholder: "Nome completo conforme OAB",
      keyboardType: "default",
      leftIcon: true,
      rightIcon: false,
      iconSize: 24,
      iconNameProps: "person",
      type: "name",
      value: name,
      onChangeText: onNameChange,
    },
    {
      label: "CPF",
      placeholder: "000.000.000-00",
      keyboardType: "numeric",
      leftIcon: true,
      rightIcon: false,
      iconSize: 24,
      iconNameProps: "badge",
      type: "cpf",
      value: cpf,
      onChangeText: onCpfChange,
    },
    {
      label: "Número OAB",
      placeholder: "000.000",
      keyboardType: "numeric",
      leftIcon: true,
      rightIcon: false,
      iconSize: 24,
      iconNameProps: "badge",
      type: "text",
      value: oabNumber,
      onChangeText: onOabNumberChange,
    },
    {
      label: "UF da OAB",
      value: uf,
      onValueChange: onUfChange,
    },
    {
      label: "Especialização Principal",
      value: specialization,
      options: specializationOptions,
      onValueChange: onSpecializationChange,
    },
    {
      label: "E-mail profissional",
      placeholder: "email@exemplo.com.br",
      keyboardType: "email-address",
      leftIcon: true,
      rightIcon: false,
      iconSize: 24,
      iconNameProps: "email",
      type: "email",
      value: email,
      onChangeText: onEmailChange,
    },
    {
      label: "Senha",
      placeholder: "••••••••",
      secureTextEntry: !showPassword,
      leftIcon: true,
      rightIcon: true,
      rightIconName: showPassword ? "visibility-off" : "visibility",
      iconSize: 24,
      iconNameProps: "lock-outline",
      type: "password",
      value: password,
      onChangeText: onPasswordChange,
      onRightIconPress: onToggleShowPassword,
    },
  ],
});
